<?php 
    function include_bootstrapCSS(){
        echo "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">";
    }

    function include_bootstrapJS(){
        echo "<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>";
        echo "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js\"></script>";
    }

    function include_bootstrapIcon(){
        echo "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">";
    }

?>